# this is NOT for secrets
variables:
  key: value

#image: docker:stable
#image: alpine:latest
#before_script:
# - apk -U add make git
 #- apt-get update --yes
 #- apt-get install --yes cmake
 #- docker info

#services:
#- docker:dind
#- docker

stages:
  - build
  - test
  #- deploy

job 1:
  stage: build
  #script: DOCKER_USERNAME="blah" echo "user=$DOCKER_USERNAME"
  script: make build

job 2:
  stage: test
  script: make test-unit

job 3:
  stage: test
  script: make test-container-scan

#job 4:
#  stage: deploy
#  script: make deploy
