stages:
  - build
  - test
  #- deploy

job 1:
  stage: build
  script: make build

job 2:
  stage: test
  script: make test-unit

job 3:
  stage: test
  script: make test-container-scan

#job 4:
#  stage: deploy
#  script: make deploy

