sudo: required
dist: trusty

# setup the basics for a nodeJS project
language: node_js
node_js:
- node

# we need docker too
services:
  - docker

# these are the pipeline stages, anything with the same name, like 'test' will be executed in parallel
jobs:
  include:
    - stage: build
      script: make build
    - stage: push
      script: make push
    - stage: test
      script: make test-unit
    - stage: test
      script: make test-container-scan
    - stage: test
      script: make test-static-code-analysis
    - stage: alert-qa
      script: make alert-qa
    - stage: Deploy to Sandbox
      script: echo "Deploying to Sandbox..."
      deploy:
        provider: openshift
        user: $OPENSHIFT_USERNAME
        password: $OPENSHIFT_PASSWORD
        domain: $OPENSHIFT_DOMAIN
        domain:
          develop: $OPENSHIFT_DOMAIN
          master: $OPENSHIFT_DOMAIN
        app:
          develop: cicd-poc1-develop
          master: cicd-poc1-master
        skip_cleanup: true
        on:
          tags: true

    #- stage: test
    #  script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt
    #- script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt


# caches speed things up?
cache:
  directories:
    - "node_modules"

addons:
  apt:
    update: true

notifications:
  slack:
    secure: ut3OGT+eA0c4bRtE5DVTOWUDxOw/mCBFcREODB//zPy3nbgD1zsuv3vC/6TgbmccmKyeG1rDMcNJ0yY/Gjv6c5aAoX2iHQYf3Wv7gkZWcki/fGvKJ5k8sjgtx6CqKXRVegIVJxlxkHKOyKvf70p8LqFfboAALYWd6Cq/hcMRRgsZEEx1lJocLrvsulbswAnRWD32GAI4GfwLBnk/wKVCPscnCX6zv1xZuI7Z5LdQ0zHjkpyBDfNw9nPBKgFvKIYqqnyxFIji7z9QHM9BM6DWqgmQQc4mO76Gq5vp7Bg3jzOIEtBVN2WRWlJMMO0DIfH1lN+/F++80ITNxTy0cbuW8e79O4n627r+zuyv+N7/M4u0raRBAEkfAwCfnSnh/AEk3MgepMRCB0R/uulHwh1XllYtd+gFJ/+GJJMI0yZgO6Db+6zH2Dz7PkqeCdpPaGSQ4NKzWDI4xk6Ms9BQ5HDwqRNojy2MlEDB2vkQSrIu62qQp/9LNipjDh3S257+NcdxhswGVKHvcPYQI17s9xBsiI68WtMVAGpoc3FhpeZaF0x1JEu/vCl7W6TGBi7myC/s3Z7vNo3+zPvrLMxLLTrD/a4DWc2ZS5Uf0xdLo4tGPbNRuSuOpWEFfpGQQQ+POq2A5H9KTU6k/kxRoXBabgRrFYCKoZWEiWaSKNHPuMLX+f4=


