- apiVersion: v1
  data:
    NEW_FEATURE: 'true'
  kind: ConfigMap
  metadata:
    name: cicdpoc1-config
    namespace: dev

- apiVersion: apps/v1beta2
  kind: Deployment
  metadata:
    labels:
      app: cicdpoc1-dev
      stack: dev
    name: cicd-poc1-dev
    namespace: dev
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: cicdpoc1-dev
    template:
      metadata:
        labels:
          app: cicdpoc1-dev
      spec:
        containers:
          - envFrom:
              - configMapRef:
                  name: cicdpoc1-config
            image: index.docker.io/natehudsonpublic/cicd-poc1
            name: primary
            ports:
              - containerPort: 8080
            readinessProbe:
              httpGet:
                path: /
                port: 8080

- apiVersion: v1
  kind: Service
  metadata:
    name: cicdpoc1-dev
    namespace: dev
  spec:
    ports:
      - port: 80
        protocol: TCP
        targetPort: 8080
    selector:
      app: cicdpoc1-dev